import { useMemo, useState } from 'react'
import { ArrowRight, Calculator, Code2, FileText, Image as ImageIcon, Moon, Search, ShieldCheck, Sparkles, Sun, Type, Upload, X, Zap } from 'lucide-react'

type Category = 'Calculators' | 'Converters' | 'Documents' | 'Developer' | 'Images' | 'Writing' | 'Generators'
type Tool = { name: string; description: string; category: Category; key: string }

const categories: {name: Category; icon: any; color: string}[] = [
  {name:'Calculators', icon:Calculator, color:'coral'}, {name:'Converters', icon:Zap, color:'teal'},
  {name:'Documents', icon:FileText, color:'violet'}, {name:'Developer', icon:Code2, color:'blue'},
  {name:'Images', icon:ImageIcon, color:'pink'}, {name:'Writing', icon:Type, color:'amber'},
  {name:'Generators', icon:Sparkles, color:'green'}
]

const rawTools: [string,string,Category,string][] = [
  ['Basic Calculator','Fast everyday arithmetic.','Calculators','basic'],['Scientific Calculator','Powers, roots and trig functions.','Calculators','scientific'],['Percentage Calculator','Find percentages instantly.','Calculators','percentage'],['EMI Calculator','Monthly EMI, interest and total payment.','Calculators','emi'],['GST Calculator','GST inclusive and exclusive amounts.','Calculators','gst'],['Discount Calculator','Discount, savings and final price.','Calculators','discount'],['Profit & Loss','Profit, loss and margin.','Calculators','profit'],['Simple Interest','Simple interest and maturity amount.','Calculators','simple-interest'],['Compound Interest','Compound growth and final amount.','Calculators','compound-interest'],['Age Calculator','Exact age from date of birth.','Calculators','age'],['SIP Calculator','Estimate SIP future value.','Calculators','sip'],['CAGR Calculator','Calculate annualized growth.','Calculators','cagr'],
  ['Length Converter','Convert m, km, ft, in and more.','Converters','length'],['Weight Converter','kg, g, lb and oz.','Converters','weight'],['Temperature Converter','Celsius, Fahrenheit and Kelvin.','Converters','temperature'],['Data Converter','Bytes through TB.','Converters','data'],['Speed Converter','km/h, mph, m/s and knots.','Converters','speed'],['Time Converter','Seconds, minutes, hours and days.','Converters','time'],
  ['Text to PDF','Turn text into a printable document.','Documents','text-pdf'],['CSV to JSON','Convert CSV data to JSON.','Documents','csv-json'],['JSON to CSV','Convert JSON arrays to CSV.','Documents','json-csv'],['Markdown to HTML','Convert simple Markdown to HTML.','Documents','md-html'],['Text File Creator','Create a downloadable text file.','Documents','text-file'],
  ['JSON Formatter','Format and validate JSON.','Developer','json-format'],['JSON Minifier','Minify JSON.','Developer','json-minify'],['Base64 Encoder','Encode UTF-8 text locally.','Developer','base64-encode'],['Base64 Decoder','Decode Base64 locally.','Developer','base64-decode'],['URL Encoder','Encode URL components.','Developer','url-encode'],['URL Decoder','Decode URL components.','Developer','url-decode'],['UUID Generator','Generate UUID v4 values.','Developer','uuid'],['Regex Tester','Test regular expressions.','Developer','regex'],['HEX to RGB','Convert HEX colors to RGB.','Developer','hex-rgb'],['SHA-256 Hash','Hash text in your browser.','Developer','sha256'],
  ['Image Compressor','Compress images in your browser.','Images','image-compress'],['Image Resizer','Resize an image locally.','Images','image-resize'],['JPG to PNG','Convert JPG to PNG locally.','Images','jpg-png'],['PNG to JPG','Convert PNG to JPG locally.','Images','png-jpg'],['WebP Converter','Convert images to WebP.','Images','webp'],['Image to Data URL','Create a data URL from an image.','Images','data-url'],
  ['Grammar Checker','Catch common grammar patterns.','Writing','grammar'],['Sentence Correction','Fix common sentence issues.','Writing','sentence'],['Word Counter','Words, characters and sentences.','Writing','word-count'],['Case Converter','UPPER, lower, Title and sentence case.','Writing','case'],['Text Cleaner','Remove extra spaces and blank lines.','Writing','clean'],['Duplicate Line Remover','Remove duplicate lines.','Writing','duplicates'],['Text Sorter','Sort lines alphabetically.','Writing','sort'],['Reading Time','Estimate reading time.','Writing','reading'],
  ['Password Generator','Strong passwords generated locally.','Generators','password'],['Random Number','Generate a random number.','Generators','random'],['Random String','Generate a random string.','Generators','string'],['Lorem Ipsum','Generate placeholder text.','Generators','lorem']
]
const tools: Tool[] = rawTools.map(([name,description,category,key])=>({name,description,category,key}))
const catIcon=(c:Category)=>categories.find(x=>x.name===c)?.icon || Sparkles
const num=(v:string)=>Number(v)||0

function ToolRunner({tool,onClose}:{tool:Tool;onClose:()=>void}) {
  const [a,setA]=useState(''); const [b,setB]=useState(''); const [c,setC]=useState(''); const [text,setText]=useState(''); const [out,setOut]=useState(''); const [file,setFile]=useState('');
  const calc=(fn:()=>string)=>{try{setOut(fn())}catch{setOut('Please enter valid values.')}}
  const download=(value:string,name:string,mime='text/plain')=>{const u=URL.createObjectURL(new Blob([value],{type:mime}));const el=document.createElement('a');el.href=u;el.download=name;el.click();URL.revokeObjectURL(u)}
  const commonText=<textarea className="tool-textarea" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste or type your text here..." />
  let body:any
  if(tool.key==='basic') body=<><input className="wide" value={text} onChange={e=>setText(e.target.value)} placeholder="Example: 125 * 4 + 20"/><button onClick={()=>calc(()=>{if(!/^[0-9+\-*/().%\s]+$/.test(text))throw 0;return String(Function('return '+text)())})}>Calculate</button></>
  else if(tool.key==='percentage') body=<><div className="fields"><label>Value<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Percentage<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(String(num(a)*num(b)/100))}>Calculate</button></>
  else if(tool.key==='emi') body=<><div className="fields"><label>Loan amount<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Annual interest %<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label><label>Years<input value={c} onChange={e=>setC(e.target.value)} type="number"/></label></div><button onClick={()=>calc(()=>{const P=num(a),r=num(b)/1200,N=num(c)*12;if(!P||!N)throw 0;const m=r?P*r*Math.pow(1+r,N)/(Math.pow(1+r,N)-1):P/N;return `Monthly EMI: ${m.toFixed(2)}\nTotal payment: ${(m*N).toFixed(2)}\nTotal interest: ${(m*N-P).toFixed(2)}`})}>Calculate EMI</button></>
  else if(tool.key==='gst') body=<><div className="fields"><label>Amount<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>GST %<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(`GST: ${(num(a)*num(b)/100).toFixed(2)}\nInclusive total: ${(num(a)*(1+num(b)/100)).toFixed(2)}`)}>Calculate</button></>
  else if(tool.key==='discount') body=<><div className="fields"><label>Price<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Discount %<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(`You save: ${(num(a)*num(b)/100).toFixed(2)}\nFinal price: ${(num(a)*(1-num(b)/100)).toFixed(2)}`)}>Calculate</button></>
  else if(tool.key==='simple-interest') body=<><div className="fields"><label>Principal<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Rate %<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label><label>Years<input value={c} onChange={e=>setC(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(`Interest: ${(num(a)*num(b)*num(c)/100).toFixed(2)}\nAmount: ${(num(a)*(1+num(b)*num(c)/100)).toFixed(2)}`)}>Calculate</button></>
  else if(tool.key==='compound-interest') body=<><div className="fields"><label>Principal<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Rate %<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label><label>Years<input value={c} onChange={e=>setC(e.target.value)} type="number"/></label></div><button onClick={()=>calc(()=>{const A=num(a)*Math.pow(1+num(b)/100,num(c));return `Final amount: ${A.toFixed(2)}\nInterest: ${(A-num(a)).toFixed(2)}`})}>Calculate</button></>
  else if(tool.key==='json-format'||tool.key==='json-minify') body=<><textarea className="tool-textarea" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste JSON..."/><button onClick={()=>calc(()=>tool.key==='json-format'?JSON.stringify(JSON.parse(text),null,2):JSON.stringify(JSON.parse(text)))}>Process JSON</button></>
  else if(tool.key==='base64-encode') body=<>{commonText}<button onClick={()=>setOut(btoa(unescape(encodeURIComponent(text))))}>Encode</button></>
  else if(tool.key==='base64-decode') body=<>{commonText}<button onClick={()=>calc(()=>decodeURIComponent(escape(atob(text.trim()))))}>Decode</button></>
  else if(tool.key==='url-encode') body=<>{commonText}<button onClick={()=>setOut(encodeURIComponent(text))}>Encode URL</button></>
  else if(tool.key==='url-decode') body=<>{commonText}<button onClick={()=>calc(()=>decodeURIComponent(text))}>Decode URL</button></>
  else if(tool.key==='word-count') body=<>{commonText}<button onClick={()=>setOut(`Words: ${text.trim()?text.trim().split(/\s+/).length:0}\nCharacters: ${text.length}\nSentences: ${(text.match(/[.!?]+/g)||[]).length}`)}>Count</button></>
  else if(tool.key==='case') body=<>{commonText}<div className="button-row"><button onClick={()=>setOut(text.toUpperCase())}>UPPERCASE</button><button onClick={()=>setOut(text.toLowerCase())}>lowercase</button><button onClick={()=>setOut(text.replace(/\w\S*/g,w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()))}>Title Case</button></div></>
  else if(tool.key==='clean') body=<>{commonText}<button onClick={()=>setOut(text.split('\n').map(x=>x.trim()).filter(Boolean).join('\n'))}>Clean text</button></>
  else if(tool.key==='duplicates') body=<>{commonText}<button onClick={()=>setOut([...new Set(text.split('\n'))].join('\n'))}>Remove duplicates</button></>
  else if(tool.key==='sort') body=<>{commonText}<button onClick={()=>setOut(text.split('\n').sort((x,y)=>x.localeCompare(y)).join('\n'))}>Sort lines</button></>
  else if(tool.key==='reading') body=<>{commonText}<button onClick={()=>setOut(`Estimated reading time: ${Math.max(1,Math.ceil((text.trim()?text.trim().split(/\s+/).length:0)/200))} minute(s)`)}>Estimate</button></>
  else if(tool.key==='password') body=<><div className="fields"><label>Length<input value={a||'16'} onChange={e=>setA(e.target.value)} type="number"/></label></div><button onClick={()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*';let s='';for(let i=0;i<Math.max(4,Math.min(128,num(a)||16));i++)s+=chars[Math.floor(Math.random()*chars.length)];setOut(s)}}>Generate password</button></>
  else if(tool.key==='random') body=<><div className="fields"><label>Min<input value={a} onChange={e=>setA(e.target.value)} type="number"/></label><label>Max<input value={b} onChange={e=>setB(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(String(Math.floor(num(a)+Math.random()*(num(b)-num(a)+1))))}>Generate</button></>
  else if(tool.key==='string') body=<><div className="fields"><label>Length<input value={a||'20'} onChange={e=>setA(e.target.value)} type="number"/></label></div><button onClick={()=>{const chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let s='';for(let i=0;i<(num(a)||20);i++)s+=chars[Math.floor(Math.random()*chars.length)];setOut(s)}}>Generate</button></>
  else if(tool.key==='lorem') body=<><div className="fields"><label>Paragraphs<input value={a||'3'} onChange={e=>setA(e.target.value)} type="number"/></label></div><button onClick={()=>setOut(Array.from({length:Math.max(1,num(a)||3)},()=>`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat, sapien at facilisis volutpat, justo neque tincidunt lorem, vitae placerat arcu erat sed nunc.`).join('\n\n'))}>Generate</button></>
  else if(tool.key==='hex-rgb') body=<><input className="wide" value={text} onChange={e=>setText(e.target.value)} placeholder="#ff6b4a"/><button onClick={()=>calc(()=>{const h=text.replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(h))throw 0;return `RGB(${parseInt(h.slice(0,2),16)}, ${parseInt(h.slice(2,4),16)}, ${parseInt(h.slice(4),16)})`})}>Convert</button></>
  else if(tool.key==='sha256') body=<>{commonText}<button onClick={async()=>{const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));setOut(Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,'0')).join(''))}}>Hash</button></>
  else if(tool.key==='text-file') body=<>{commonText}<button onClick={()=>download(text,'toolsnextgen.txt')}>Download TXT</button></>
  else if(tool.key==='text-pdf') body=<><p className="muted">Paste text below. A print-ready document will open in your browser; choose “Save as PDF”.</p>{commonText}<button onClick={()=>{const w=window.open('','_blank');if(w){w.document.write(`<pre style="white-space:pre-wrap;font:16px Arial;padding:40px">${text.replace(/</g,'&lt;')}</pre>`);w.document.close();w.print()}}}>Create printable PDF</button></>
  else if(tool.key==='csv-json') body=<>{commonText}<button onClick={()=>calc(()=>{const rows=text.trim().split(/\r?\n/).map(r=>r.split(',').map(x=>x.trim()));const h=rows.shift()||[];return JSON.stringify(rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||'']))),null,2)})}>Convert</button></>
  else if(tool.key==='json-csv') body=<>{commonText}<button onClick={()=>calc(()=>{const arr=JSON.parse(text);if(!Array.isArray(arr)||!arr.length)throw 0;const h=Object.keys(arr[0]);return [h.join(','),...arr.map(r=>h.map(k=>String(r[k]??'').replaceAll(',',' ')).join(','))].join('\n')})}>Convert</button></>
  else if(tool.key==='md-html') body=<>{commonText}<button onClick={()=>setOut(text.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\n/g,'<br>'))}>Convert</button></>
  else if(tool.key==='image-compress'||tool.key==='image-resize'||tool.key==='jpg-png'||tool.key==='png-jpg'||tool.key==='webp'||tool.key==='data-url') body=<><label className="drop"><Upload size={26}/><span>{file||'Choose an image'}</span><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]?.name||'')}/></label><p className="muted">Image processing is designed to run locally in your browser. Full canvas controls are being added to this workspace.</p></>
  else if(tool.key==='grammar'||tool.key==='sentence') body=<>{commonText}<button onClick={()=>setOut(text.replace(/\bi\b/g,'I').replace(/\s+/g,' ').trim())}>Check & improve</button></>
  else body=<>{commonText}<button onClick={()=>setOut(text)}>Process</button></>
  return <div className="tool-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="tool-modal"><header><div><span className="modal-kicker">TOOLSNEXTGEN • {tool.category}</span><h2>{tool.name}</h2><p>{tool.description}</p></div><button className="close" onClick={onClose}><X/></button></header><div className="runner">{body}{out&&<div className="result"><div className="result-top"><strong>Result</strong><button onClick={()=>navigator.clipboard?.writeText(out)}>Copy</button></div><pre>{out}</pre><button className="download" onClick={()=>download(out,`${tool.key}-result.txt`)}>Download result</button></div>}</div></section></div>
}

function App(){
 const [dark,setDark]=useState(false); const [active,setActive]=useState<Category|'All'>('All'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Tool|null>(null);
 const filtered=useMemo(()=>tools.filter(t=>(active==='All'||t.category===active)&&(!query||(t.name+' '+t.description+' '+t.category).toLowerCase().includes(query.toLowerCase()))),[active,query]);
 return <div className={dark?'app dark':'app'}>
  <header className="top"><div className="top-inner"><button className="logo" onClick={()=>{setActive('All');setQuery('')}}><span className="logo-mark"><Sparkles size={18}/></span><span>Tools<span>NextGen</span></span></button><nav>{categories.slice(0,5).map(c=><button key={c.name} className={active===c.name?'active':''} onClick={()=>setActive(c.name)}>{c.name}</button>)}<button onClick={()=>setActive('All')}>All Tools</button></nav><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></div></header>
  <main>
   <section className="hero"><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-content"><div className="badge"><span>✦</span> The modern utility workspace</div><h1>Do more.<br/><span>Switch less.</span></h1><p>Calculators, converters, documents, images, writing and developer utilities — all in one fast workspace.</p><div className="search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What do you need to do? Try “EMI”, “PDF”, “JSON”..."/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><div className="hero-pills"><span><ShieldCheck size={15}/> Privacy-first</span><span><Zap size={15}/> Fast & free</span><span><Sparkles size={15}/> No sign-up</span></div></div></section>
   <section className="workspace"><aside><div className="side-title">Explore</div><button className={active==='All'?'side active':'side'} onClick={()=>setActive('All')}>All tools <b>{tools.length}</b></button>{categories.map(c=>{const I=c.icon;return <button key={c.name} className={active===c.name?'side active':'side'} onClick={()=>setActive(c.name)}><span><I size={17}/>{c.name}</span><b>{tools.filter(t=>t.category===c.name).length}</b></button>})}<div className="side-note"><ShieldCheck size={18}/><strong>Private by design</strong><p>Browser-first utilities keep your data on your device whenever possible.</p></div></aside><div className="results"><div className="results-head"><div><span className="eyebrow">{active==='All'?'EVERYTHING':'CATEGORY'}</span><h2>{active==='All'?'Your tools, your way':active}</h2></div><span className="count">{filtered.length} tools</span></div>{filtered.length?<div className="grid">{filtered.map(t=>{const I=catIcon(t.category);return <button className="card" key={t.key} onClick={()=>setSelected(t)}><span className={`card-icon ${categories.find(c=>c.name===t.category)?.color}`}><I size={20}/></span><span className="card-copy"><strong>{t.name}</strong><small>{t.description}</small></span><ArrowRight className="arrow" size={17}/></button>})}</div>:<div className="empty"><Search size={30}/><h3>No tool found</h3><p>Try another search term.</p></div>}</div></section>
   <section className="workflow"><div><span className="eyebrow">BUILT DIFFERENT</span><h2>One workspace.<br/><em>Zero tool hopping.</em></h2></div><div className="steps"><div><b>01</b><strong>Find</strong><p>Tell us what you need.</p></div><div><b>02</b><strong>Use</strong><p>Tool opens right here.</p></div><div><b>03</b><strong>Finish</strong><p>Copy, download or continue.</p></div></div></section>
  </main>
  <footer><div><button className="logo footer-logo" onClick={()=>setActive('All')}><span className="logo-mark"><Sparkles size={18}/></span><span>Tools<span>NextGen</span></span></button><p>Useful tools for the next generation of the internet.</p></div><div className="footer-links"><strong>Categories</strong>{categories.map(c=><button key={c.name} onClick={()=>setActive(c.name)}>{c.name}</button>)}</div><div className="footer-bottom">© 2026 ToolsNextGen <span>Free • Fast • Privacy-first</span></div></footer>
  {selected&&<ToolRunner tool={selected} onClose={()=>setSelected(null)}/>} 
 </div>
}
export default App
