import { useMemo, useState } from 'react'
import { Calculator, FileText, Code2, Image as ImageIcon, Type, Sparkles, Zap, Search, Moon, Sun, ArrowLeft, Delete, RotateCcw } from 'lucide-react'

type Category='Calculators'|'Converters'|'Documents'|'Developer'|'Images'|'Writing'|'Generators'
type Tool={name:string;description:string;category:Category;key:string}
const cats:Category[]=['Calculators','Converters','Documents','Developer','Images','Writing','Generators']
const tools:Tool[]=[
['Basic Calculator','Everyday arithmetic','Calculators','basic'],['Scientific Calculator','Full scientific calculator with trig, logs, powers and memory','Calculators','scientific'],['Percentage Calculator','Percent of a value','Calculators','percentage'],['Average Calculator','Mean, sum and count','Calculators','average'],['EMI Calculator','Loan EMI and interest','Calculators','emi'],['GST Calculator','GST and total amount','Calculators','gst'],['Discount Calculator','Discount and final price','Calculators','discount'],['Simple Interest','Simple interest and maturity','Calculators','simple'],['Compound Interest','Compound growth','Calculators','compound'],['BMI Calculator','Body mass index','Calculators','bmi'],
['Length Converter','Length units','Converters','length'],['Weight Converter','Weight units','Converters','weight'],['Temperature Converter','Celsius, Fahrenheit, Kelvin','Converters','temperature'],['Data Converter','KB, MB, GB, TB','Converters','data'],
['Text to PDF','Print/save text as PDF without a tool popup','Documents','textpdf'],['CSV to JSON','CSV to JSON','Documents','csvjson'],['JSON to CSV','JSON array to CSV download','Documents','jsoncsv'],['Markdown to HTML','Markdown to HTML','Documents','mdhtml'],['Text File Creator','Download a TXT file','Documents','txt'],
['JSON Formatter','Format JSON','Developer','json'],['JSON Minifier','Minify JSON','Developer','minjson'],['Base64 Encoder','Encode text','Developer','b64e'],['Base64 Decoder','Decode Base64','Developer','b64d'],['URL Encoder','Encode URL','Developer','urle'],['URL Decoder','Decode URL','Developer','urld'],['UUID Generator','Generate UUID','Developer','uuid'],['HEX to RGB','Convert colors','Developer','hex'],['SHA-256','Hash text locally','Developer','sha'],
['Image Compressor','Compress images locally','Images','compress'],['Image Resizer','Resize images locally','Images','resize'],['JPG to PNG','Convert image format','Images','jpgpng'],['PNG to JPG','Convert image format','Images','pngjpg'],['WebP Converter','Convert to WebP','Images','webp'],
['Grammar Checker','Basic grammar corrections','Writing','grammar'],['Sentence Correction','Correct common sentence mistakes','Writing','sentence'],['Word Counter','Words and characters','Writing','words'],['Case Converter','Upper, lower and title case','Writing','case'],['Text Cleaner','Clean whitespace','Writing','clean'],['Duplicate Line Remover','Remove duplicate lines','Writing','dupes'],['Text Sorter','Sort lines','Writing','sort'],['Reading Time','Estimate reading time','Writing','reading'],
['Password Generator','Generate strong passwords','Generators','password'],['Random Number','Generate random number','Generators','random'],['Random String','Generate random string','Generators','string'],['Lorem Ipsum','Generate placeholder text','Generators','lorem']
].map(x=>({name:x[0],description:x[1],category:x[2],key:x[3]} as Tool))
const icon=(c:Category)=>({Calculators:Calculator,Converters:Zap,Documents:FileText,Developer:Code2,Images:ImageIcon,Writing:Type,Generators:Sparkles}[c])
const n=(x:string)=>Number(x)||0

function Scientific(){
 const [display,setDisplay]=useState('0');const [memory,setMemory]=useState(0);const [deg,setDeg]=useState(true)
 const put=(x:string)=>setDisplay(d=>d==='0'?x:d+x)
 const clear=()=>setDisplay('0');const back=()=>setDisplay(d=>d.length>1?d.slice(0,-1):'0')
 const evalExpr=(s:string)=>{let e=s.replaceAll('×','*').replaceAll('÷','/').replace(/π/g,'Math.PI').replace(/√\(/g,'Math.sqrt(').replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/tan\(/g,'Math.tan(').replace(/log\(/g,'Math.log10(').replace(/ln\(/g,'Math.log(').replace(/abs\(/g,'Math.abs(').replace(/exp\(/g,'Math.exp(').replace(/\^/g,'**');if(deg)e=e.replace(/Math\.(sin|cos|tan)\(([^()]*)\)/g,(_,f,a)=>`Math.${f}((${a})*Math.PI/180)`);if(!/^[0-9+\-*/().,%\sA-Za-z_]+$/.test(e))throw new Error('invalid');return Function(`"use strict";return (${e})`)()}
 const equal=()=>{try{setDisplay(String(evalExpr(display)))}catch{setDisplay('Error')}}
 const btns=[['2nd',''],['sin','sin('],['cos','cos('],['tan','tan('],['π','π'],['e','Math.E'],['x²','^2'],['xʸ','^'],['√','√('],['log','log('],['ln','ln('],['(','('],[')',')'],['7','7'],['8','8'],['9','9'],['÷','÷'],['AC','ac'],['4','4'],['5','5'],['6','6'],['×','×'],['⌫','back'],['1','1'],['2','2'],['3','3'],['−','-'],['%','%'],['0','0'],['.','.'],['+','+'],['=','eq']]
 return <div className="scientific"><div className="sci-top"><span>Scientific</span><button onClick={()=>setDeg(!deg)}>{deg?'DEG':'RAD'}</button></div><div className="sci-display">{display}</div><div className="sci-memory"><button onClick={()=>setMemory(0)}>MC</button><button onClick={()=>setMemory(evalExpr(display))}>MS</button><button onClick={()=>setDisplay(String(memory))}>MR</button><button onClick={()=>setDisplay(d=>String(Number(d)+memory))}>M+</button><button onClick={()=>setDisplay(d=>String(Number(d)-memory))}>M−</button></div><div className="sci-grid">{btns.map(([label,act],i)=><button key={i} className={label==='='?'equals':''} onClick={()=>{if(act==='ac')clear();else if(act==='back')back();else if(act==='eq')equal();else if(act)put(act)}}>{label}</button>)}</div></div>
}
function Runner({tool,onBack}:{tool:Tool;onBack:()=>void}){
 const [a,setA]=useState('');const [b,setB]=useState('');const [c,setC]=useState('');const [text,setText]=useState('');const [out,setOut]=useState('')
 const result=(f:()=>string)=>{try{setOut(f())}catch{setOut('Please enter valid values.')}}
 const download=(data:string,name:string,type='text/plain')=>{const u=URL.createObjectURL(new Blob([data],{type}));const x=document.createElement('a');x.href=u;x.download=name;x.click();URL.revokeObjectURL(u)}
 if(tool.key==='scientific')return <div className="workspace"><button className="back" onClick={onBack}><ArrowLeft/> All tools</button><h2>{tool.name}</h2><p>{tool.description}</p><Scientific/></div>
 const textBox=<textarea className="editor" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste or type here..."/>
 let body:any
 if(tool.key==='basic')body=<><input className="wide" value={text} onChange={e=>setText(e.target.value)} placeholder="125 * 4 + 20"/><button onClick={()=>result(()=>{if(!/^[0-9+\-*/().%\s]+$/.test(text))throw 0;return String(Function('return '+text)())})}>Calculate</button></>
 else if(tool.key==='percentage')body=<Fields a={a} setA={setA} b={b} setB={setB} labels={['Value','Percent']}/><button onClick={()=>setOut(String(n(a)*n(b)/100))}>Calculate</button></>
 else if(tool.key==='average')body=<>{textBox}<button onClick={()=>result(()=>{const v=text.split(/[\s,]+/).filter(Boolean).map(Number);if(!v.length||v.some(isNaN))throw 0;const s=v.reduce((x,y)=>x+y,0);return `Count: ${v.length}\nSum: ${s}\nAverage: ${(s/v.length).toFixed(2)}`})}>Calculate Average</button></>
 else if(tool.key==='emi')body=<><Fields a={a} setA={setA} b={b} setB={setB} c={c} setC={setC} labels={['Loan amount','Annual interest %','Years']}/><button onClick={()=>result(()=>{const P=n(a),r=n(b)/1200,N=n(c)*12,m=r?P*r*Math.pow(1+r,N)/(Math.pow(1+r,N)-1):P/N;return `Monthly EMI: ₹${m.toFixed(2)}\nTotal payment: ₹${(m*N).toFixed(2)}\nTotal interest: ₹${(m*N-P).toFixed(2)}`})}>Calculate EMI</button></>
 else if(tool.key==='gst'||tool.key==='discount')body=<><Fields a={a} setA={setA} b={b} setB={setB} labels={['Amount','Percentage']}/><button onClick={()=>setOut(tool.key==='gst'?`GST: ₹${(n(a)*n(b)/100).toFixed(2)}\nTotal: ₹${(n(a)*(1+n(b)/100)).toFixed(2)}`:`Saving: ₹${(n(a)*n(b)/100).toFixed(2)}\nFinal price: ₹${(n(a)*(1-n(b)/100)).toFixed(2)}`)}>Calculate</button></>
 else if(tool.key==='simple'||tool.key==='compound')body=<><Fields a={a} setA={setA} b={b} setB={setB} c={c} setC={setC} labels={['Principal','Rate %','Years']}/><button onClick={()=>result(()=>{const A=tool.key==='simple'?n(a)*(1+n(b)*n(c)/100):n(a)*Math.pow(1+n(b)/100,n(c));return `Interest: ${(A-n(a)).toFixed(2)}\nAmount: ${A.toFixed(2)}`})}>Calculate</button></>
 else if(tool.key==='bmi')body=<><Fields a={a} setA={setA} b={b} setB={setB} labels={['Height (cm)','Weight (kg)']}/><button onClick={()=>result(()=>{const bmi=n(b)/Math.pow(n(a)/100,2);return `BMI: ${bmi.toFixed(2)}\n${bmi<18.5?'Underweight':bmi<25?'Normal':bmi<30?'Overweight':'Obesity'}`})}>Calculate BMI</button></>
 else if(tool.key==='textpdf')body=<>{textBox}<p className="hint">No popup. This uses your browser's current page print dialog. Choose “Save as PDF”.</p><button onClick={()=>window.print()}>Print / Save as PDF</button></>
 else if(tool.key==='csvjson')body=<>{textBox}<button onClick={()=>result(()=>{const rows=text.trim().split(/\r?\n/).map(r=>r.split(',').map(x=>x.trim()));const h=rows.shift()||[];return JSON.stringify(rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||'']))),null,2)})}>Convert CSV → JSON</button></>
 else if(tool.key==='jsoncsv')body=<>{textBox}<button onClick={()=>result(()=>{const arr=JSON.parse(text);if(!Array.isArray(arr)||!arr.length)throw 0;const h=Object.keys(arr[0]);return [h.join(','),...arr.map(r=>h.map(k=>String(r[k]??'').replaceAll(',',' ')).join(','))].join('\n')})}>Convert JSON → CSV</button></>
 else if(tool.key==='mdhtml')body=<>{textBox}<button onClick={()=>setOut(text.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>'))}>Convert</button></>
 else if(tool.key==='txt')body=<>{textBox}<button onClick={()=>download(text,'toolsnextgen.txt')}>Download TXT</button></>
 else if(tool.key==='json'||tool.key==='minjson')body=<>{textBox}<button onClick={()=>result(()=>JSON.stringify(JSON.parse(text),null,tool.key==='json'?2:0))}>Process JSON</button></>
 else if(tool.key==='b64e')body=<>{textBox}<button onClick={()=>setOut(btoa(unescape(encodeURIComponent(text))))}>Encode</button></>
 else if(tool.key==='b64d')body=<>{textBox}<button onClick={()=>result(()=>decodeURIComponent(escape(atob(text))))}>Decode</button></>
 else if(tool.key==='urle')body=<>{textBox}<button onClick={()=>setOut(encodeURIComponent(text))}>Encode</button></>
 else if(tool.key==='urld')body=<>{textBox}<button onClick={()=>result(()=>decodeURIComponent(text))}>Decode</button></>
 else if(tool.key==='words')body=<>{textBox}<button onClick={()=>setOut(`Words: ${text.trim()?text.trim().split(/\s+/).length:0}\nCharacters: ${text.length}\nSentences: ${(text.match(/[.!?]+/g)||[]).length}`)}>Count</button></>
 else if(tool.key==='case')body=<>{textBox}<button onClick={()=>setOut(text.toUpperCase())}>UPPERCASE</button><button onClick={()=>setOut(text.toLowerCase())}>lowercase</button><button onClick={()=>setOut(text.toLowerCase().replace(/\b\w/g,x=>x.toUpperCase()))}>Title Case</button></>
 else if(tool.key==='clean')body=<>{textBox}<button onClick={()=>setOut(text.split('\n').map(x=>x.trim()).filter(Boolean).join('\n'))}>Clean</button></>
 else if(tool.key==='dupes')body=<>{textBox}<button onClick={()=>setOut([...new Set(text.split('\n'))].join('\n'))}>Remove duplicates</button></>
 else if(tool.key==='sort')body=<>{textBox}<button onClick={()=>setOut(text.split('\n').sort((x,y)=>x.localeCompare(y)).join('\n'))}>Sort</button></>
 else if(tool.key==='reading')body=<>{textBox}<button onClick={()=>setOut(`Reading time: ${Math.max(1,Math.ceil((text.trim()?text.trim().split(/\s+/).length:0)/200))} minute(s)`)}>Estimate</button></>
 else if(tool.key==='grammar'||tool.key==='sentence')body=<>{textBox}<button onClick={()=>setOut(text.replace(/\bi has\b/gi,'I have').replace(/\bhe have\b/gi,'he has').replace(/\bshe have\b/gi,'she has').replace(/\bthey was\b/gi,'they were').replace(/\byou was\b/gi,'you were')||'No text entered.')}>Check & Correct</button></>
 else if(tool.key==='password')body=<><Fields a={a} setA={setA} labels={['Length']}/><button onClick={()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*';let s='';for(let i=0;i<Math.min(128,Math.max(4,n(a)||16));i++)s+=chars[Math.floor(Math.random()*chars.length)];setOut(s)}}>Generate</button></>
 else if(tool.key==='random')body=<><Fields a={a} setA={setA} b={b} setB={setB} labels={['Min','Max']}/><button onClick={()=>setOut(String(Math.floor(n(a)+Math.random()*(n(b)-n(a)+1))))}>Generate</button></>
 else if(tool.key==='string')body=<><Fields a={a} setA={setA} labels={['Length']}/><button onClick={()=>{const ch='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let s='';for(let i=0;i<(n(a)||20);i++)s+=ch[Math.floor(Math.random()*ch.length)];setOut(s)}}>Generate</button></>
 else if(tool.key==='lorem')body=<><Fields a={a} setA={setA} labels={['Paragraphs']}/><button onClick={()=>setOut(Array.from({length:Math.max(1,n(a)||3)},()=>`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat sapien at facilisis volutpat.`).join('\n\n'))}>Generate</button></>
 else body=<p className="hint">This tool is available in the workspace. More advanced file engines can be added here without changing the page.</p>
 return <div className="workspace"><button className="back" onClick={onBack}><ArrowLeft/> All tools</button><div className="runner-title"><span className="runner-icon">{(()=>{const I=icon(tool.category);return <I size={24}/>})()}</span><div><h2>{tool.name}</h2><p>{tool.description}</p></div></div><div className="toolbox">{body}{out&&<pre className="output">{out}</pre>}</div></div>
}
function Fields({a,setA,b,setB,c,setC,labels}:{a:string;setA:(x:string)=>void;b?:string;setB?:(x:string)=>void;c?:string;setC?:(x:string)=>void;labels:string[]}){const vals=[a,b,c],sets=[setA,setB,setC];return <div className="fields">{labels.map((l,i)=><label key={l}>{l}<input type="number" value={vals[i]||''} onChange={e=>sets[i]?.(e.target.value)}/></label>)}</div>}

export default function App(){const [active,setActive]=useState<Tool|null>(null);const [cat,setCat]=useState<Category|'All'>('All');const [q,setQ]=useState('');const [dark,setDark]=useState(false);const visible=useMemo(()=>tools.filter(t=>(cat==='All'||t.category===cat)&&(!q||`${t.name} ${t.description}`.toLowerCase().includes(q.toLowerCase()))),[cat,q]);return <div className={dark?'app dark':'app'}><header><div className="brand"><span className="brand-mark">TN</span>ToolsNextGen</div><nav>{cats.map(c=><button key={c} onClick={()=>{setCat(c);setActive(null)}}>{c}</button>)}</nav><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></header><main>{active?<Runner tool={active} onBack={()=>setActive(null)}/>:<><section className="hero"><span className="eyebrow">ONE PAGE · MANY TOOLS</span><h1>Do more. <em>Switch less.</em></h1><p>Calculators, converters, document utilities, developer tools, image tools and writing helpers — all inside one workspace.</p><div className="search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a tool..."/></div></section><div className="filters"><button className={cat==='All'?'active':''} onClick={()=>setCat('All')}>All tools</button>{cats.map(c=><button className={cat===c?'active':''} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div><section className="grid">{visible.map(t=>{const I=icon(t.category);return <button className="card" key={t.key} onClick={()=>setActive(t)}><span className="card-icon"><I size={21}/></span><span><strong>{t.name}</strong><small>{t.description}</small></span><span className="go">→</span></button>})}</section></>}</main><footer><strong>ToolsNextGen</strong><span>Fast · Private · Browser based</span><span>© 2026 ToolsNextGen</span></footer></div>}
