import {useMemo,useState} from 'react'
import {Link,useLocation} from 'react-router-dom'
import {ArrowRight,Calculator,Code2,FileText,Image as ImageIcon,Menu,Moon,Search,ShieldCheck,Sparkles,Sun,Type,Upload,Download,X,Zap} from 'lucide-react'

type Tool={name:string;description:string;path:string;category:string}
const CATS=['Calculators','Converters','Document Tools','Developer Tools','Image Tools','Grammar & Language','Generators']
const slug=(s:string)=>s.toLowerCase().replace(/ & /g,'-').replace(/ /g,'-')
const icon=(c:string)=>c==='Calculators'?Calculator:c==='Converters'?Zap:c==='Document Tools'?FileText:c==='Developer Tools'?Code2:c==='Image Tools'?ImageIcon:c==='Grammar & Language'?Type:Sparkles
const make=(category:string,items:[string,string,string][])=>items.map(([n,d,p])=>({name:n,description:d,path:p,category}))
const catalog:Tool[]=[
...make('Calculators',[
['Basic Calculator','Fast arithmetic calculator.','basic-calculator'],['Scientific Calculator','Scientific functions, powers and roots.','scientific-calculator'],['Percentage Calculator','Find percentages, increase and decrease.','percentage-calculator'],['GST Calculator','Calculate GST inclusive and exclusive prices.','gst-calculator'],['EMI Calculator','Calculate monthly EMI, interest and total payment.','emi-calculator'],['Simple Interest Calculator','Calculate simple interest and maturity value.','simple-interest-calculator'],['Compound Interest Calculator','Calculate compound interest and final amount.','compound-interest-calculator'],['Age Calculator','Calculate exact age from date of birth.','age-calculator'],['Discount Calculator','Calculate discount amount and final price.','discount-calculator'],['Profit & Loss Calculator','Calculate profit, loss and margin.','profit-loss-calculator'],['Ratio Calculator','Simplify and compare ratios.','ratio-calculator'],['Average Calculator','Calculate average, sum, minimum and maximum.','average-calculator'],['BMI Calculator','Calculate BMI from height and weight.','bmi-calculator'],['BMR Calculator','Estimate basal metabolic rate.','bmr-calculator'],['SIP Calculator','Estimate SIP future value.','sip-calculator'],['FD Calculator','Estimate fixed deposit maturity.','fd-calculator'],['CAGR Calculator','Calculate compound annual growth rate.','cagr-calculator'],['Date Difference','Calculate days between two dates.','date-difference'],['Time Duration Calculator','Calculate duration between times.','time-duration'],['Fraction Calculator','Add, subtract, multiply and divide fractions.','fraction-calculator'],['GCD & LCM Calculator','Calculate greatest common divisor and least common multiple.','gcd-lcm'],['Square Root Calculator','Calculate square roots instantly.','square-root'],['Random Number Calculator','Generate a random number in a range.','random-number']].map(x=>[x[0],x[1],'/calculators/'+x[2]])),
...make('Converters',[
['Length Converter','Meters, kilometers, feet, inches and more.','length-converter'],['Weight Converter','Kilograms, grams, pounds and ounces.','weight-converter'],['Temperature Converter','Celsius, Fahrenheit and Kelvin.','temperature-converter'],['Area Converter','Square meters, feet, acres and more.','area-converter'],['Volume Converter','Liters, gallons and cubic units.','volume-converter'],['Speed Converter','km/h, mph, m/s and knots.','speed-converter'],['Time Converter','Seconds, minutes, hours and days.','time-converter'],['Data Converter','Bytes, KB, MB, GB and TB.','data-converter'],['Number to Words','Convert numbers into English words.','number-to-words'],['Roman Numeral Converter','Number to Roman and Roman to number.','roman-numeral'],['Base Converter','Binary, decimal, hexadecimal and octal.','base-converter'],['Currency Converter','Simple currency conversion interface.','currency-converter']].map(x=>[x[0],x[1],'/converters/'+x[2]])),
...make('Document Tools',[
['Text to PDF','Create a printable PDF from text using your browser.','text-to-pdf'],['CSV to JSON','Convert CSV data into JSON.','csv-to-json'],['JSON to CSV','Convert JSON arrays into CSV.','json-to-csv'],['Markdown to HTML','Convert basic Markdown into HTML.','markdown-to-html'],['Text File Creator','Create and download a TXT file.','text-file-creator'],['CSV Viewer','Paste CSV and preview rows.','csv-viewer']].map(x=>[x[0],x[1],'/documents/'+x[2]])),
...make('Developer Tools',[
['JSON Formatter','Format and validate JSON.','json-formatter'],['JSON Minifier','Minify JSON.','json-minifier'],['HTML Formatter','Basic HTML beautifier.','html-formatter'],['CSS Formatter','Basic CSS beautifier.','css-formatter'],['JavaScript Formatter','Basic JavaScript beautifier.','javascript-formatter'],['Base64 Encoder','Encode UTF-8 text to Base64.','base64-encoder'],['Base64 Decoder','Decode Base64 to UTF-8 text.','base64-decoder'],['URL Encoder','Encode URL components.','url-encoder'],['URL Decoder','Decode URL components.','url-decoder'],['UUID Generator','Generate UUID v4 values.','uuid-generator'],['Regex Tester','Test a regular expression.','regex-tester'],['HEX to RGB','Convert HEX colors to RGB.','color-converter'],['Timestamp Converter','Convert Unix timestamps and dates.','timestamp-converter'],['HTML Entity Encoder','Encode special HTML characters.','html-entity'],['Text Hash','Generate SHA-256 hash in browser.','sha256']].map(x=>[x[0],x[1],'/developer/'+x[2]])),
...make('Image Tools',[
['Image Compressor','Compress JPG, PNG or WebP in your browser.','image-compressor'],['Image Resizer','Resize an image to exact dimensions.','image-resizer'],['Image Cropper','Crop an image using a simple canvas editor.','image-cropper'],['JPG to PNG','Convert JPG images to PNG.','jpg-to-png'],['PNG to JPG','Convert PNG images to JPG.','png-to-jpg'],['WebP Converter','Convert images to WebP.','webp-converter'],['Image to Data URL','Convert an image into a Data URL.','image-data-url']].map(x=>[x[0],x[1],'/image/'+x[2]])),
...make('Grammar & Language',[
['Grammar Checker','Check common spelling and grammar patterns.','grammar-checker'],['Sentence Correction','Detect common sentence issues.','sentence-correction'],['Spell Checker','Find common spelling mistakes.','spell-checker'],['Word Counter','Count words, characters and sentences.','word-counter'],['Reading Time','Estimate reading time.','reading-time'],['Case Converter','Uppercase, lowercase, title case and sentence case.','case-converter'],['Text Cleaner','Remove extra spaces and blank lines.','text-cleaner'],['Duplicate Line Remover','Remove duplicate lines.','duplicate-lines'],['Text Sorter','Sort lines alphabetically.','text-sorter'],['Lorem Ipsum Generator','Generate placeholder text.','lorem-ipsum'],['Reverse Text','Reverse characters or lines.','reverse-text'],['Sentence Counter','Count sentences and paragraphs.','sentence-counter']].map(x=>[x[0],x[1],'/grammar/'+x[2]])),
...make('Generators',[
['Password Generator','Generate strong passwords locally.','password-generator'],['Random Number Generator','Generate random numbers.','random-number'],['Random String Generator','Generate random strings.','random-string'],['UUID Generator','Generate unique UUIDs.','uuid-generator'],['Lorem Ipsum Generator','Generate placeholder paragraphs.','lorem-ipsum'],['QR Code Generator','Generate a QR image from a URL or text.','qr-code']].map(x=>[x[0],x[1],'/generators/'+x[2]]))
]

function Header({dark,setDark}:{dark:boolean;setDark:(x:boolean)=>void}){const[open,setOpen]=useState(false);const[q,setQ]=useState('');const results=useMemo(()=>q?catalog.filter(t=>(t.name+' '+t.category+' '+t.description).toLowerCase().includes(q.toLowerCase())).slice(0,8):[],[q]);return <header className="header"><div className="container nav"><Link className="brand" to="/" onClick={()=>setOpen(false)}><span className="brand-mark"><Sparkles size={18}/></span><span>Tool<span>Box</span></span></Link><nav className={'nav-links '+(open?'open':'')}>{CATS.slice(0,5).map(c=><Link key={c} to={'/'+slug(c)} onClick={()=>setOpen(false)}>{c}</Link>)}<Link to="/tools" onClick={()=>setOpen(false)}>All Tools</Link></nav><div className="nav-actions"><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div><div className="global-search container"><div className="search-wrap"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search all tools..."/>{q&&<button className="clear" onClick={()=>setQ('')}><X size={16}/></button>}{results.length>0&&<div className="search-results">{results.map(t=>{const I=icon(t.category);return <Link key={t.path} to={t.path} onClick={()=>setQ('')}><I size={17}/><span><b>{t.name}</b><small>{t.category}</small></span><ArrowRight size={15}/></Link>})}</div>}</div></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-main"><div className="footer-brand"><Link className="brand" to="/"><span className="brand-mark"><Sparkles size={18}/></span><span>Tool<span>Box</span></span></Link><p>Free, fast and privacy-first online utilities.</p></div>{CATS.slice(0,4).map(c=><div className="footer-col" key={c}><h4>{c}</h4>{catalog.filter(t=>t.category===c).slice(0,5).map(t=><Link key={t.path} to={t.path}>{t.name}</Link>)}</div>)}</div><div className="container footer-bottom"><span>© 2026 ToolBox</span><span>Free • Fast • Privacy-first</span></div></footer>}
function Card({t}:{t:Tool}){const I=icon(t.category);return <Link className="tool-card" to={t.path}><span className="tool-icon"><I size={20}/></span><div><h3>{t.name}</h3><p>{t.description}</p></div><ArrowRight className="card-arrow" size={17}/></Link>}
function Category({category}:{category:string}){const list=catalog.filter(t=>t.category===category);const I=icon(category);return <main><section className="page-hero"><div className="container"><p className="kicker">TOOL CATEGORY</p><div className="title-line"><span className="category-icon"><I/></span><h1>{category}</h1></div><p>All {category.toLowerCase()} in one place. Choose a tool and start instantly.</p></div></section><section className="section container"><div className="tool-grid">{list.map(t=><Card t={t} key={t.path}/>)}</div></section></main>}
function Home(){return <main><section className="hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="container hero-inner"><div className="eyebrow"><span><Zap size={13}/> 100+ tools planned</span><span><ShieldCheck size={13}/> Privacy-first</span></div><h1>One place for <em>everyday tools.</em></h1><p className="hero-copy">Calculators, converters, document utilities, developer tools, image tools and language helpers — fast, free and easy to use.</p><div className="hero-cta"><Link to="/tools">Explore all tools <ArrowRight size={16}/></Link><Link className="secondary" to="/calculators">Browse calculators</Link></div></div></section><section className="section container"><div className="section-head"><div><p className="kicker">EXPLORE</p><h2>Tool categories</h2></div></div><div className="category-grid">{CATS.map(c=>{const I=icon(c);return <Link className="category-card" key={c} to={'/'+slug(c)}><span className="category-icon"><I/></span><div><h3>{c}</h3><p>{catalog.filter(t=>t.category===c).length} tools</p></div><ArrowRight className="card-arrow" size={18}/></Link>})}</div></section><section className="section container"><div className="section-head"><div><p className="kicker">POPULAR</p><h2>Start with these</h2></div><Link className="view-all" to="/tools">View all <ArrowRight size={15}/></Link></div><div className="tool-grid">{catalog.slice(0,12).map(t=><Card t={t} key={t.path}/>)}</div></section><section className="trust-section"><div className="container trust-grid"><div><span className="trust-icon"><ShieldCheck/></span><div><h3>Privacy-first</h3><p>Browser-based tools whenever possible.</p></div></div><div><span className="trust-icon"><Zap/></span><div><h3>Fast</h3><p>No account required for basic utilities.</p></div></div><div><span className="trust-icon"><Sparkles/></span><div><h3>Always growing</h3><p>New tools and improvements regularly.</p></div></div></div></section></main>}

function Input({label,value,setValue,type='text'}:{label:string;value:string;setValue:(x:string)=>void;type?:string}){return <label className="field">{label}<input type={type} value={value} onChange={e=>setValue(e.target.value)}/></label>}
const n=(x:string)=>Number(x)||0
function DownloadText({text,name='result.txt'}:{text:string;name?:string}){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));return <a className="download" href={url} download={name}><Download size={16}/> Download</a>}
function ToolPage({tool}:{tool:Tool}){const[text,setText]=useState('');const[a,setA]=useState('');const[b,setB]=useState('');const[c,setC]=useState('');const[d,setD]=useState('');const[result,setResult]=useState('');const[error,setError]=useState('');const path=tool.path;const run=(fn:()=>string)=>{try{setError('');setResult(fn())}catch{setError('Please enter valid values.');setResult('')}}
let body:any;
if(path.includes('basic-calculator')) body=<><Input label="Expression (example: 125 * 4 + 20)" value={text} setValue={setText}/><button onClick={()=>run(()=>{if(!/^[0-9+\-*/().%\s]+$/.test(text))throw 0;return String(Function('return '+text)())})}>Calculate</button></>;
else if(path.includes('scientific-calculator')) body=<><Input label="Expression (sin, cos, sqrt, pow supported)" value={text} setValue={setText}/><button onClick={()=>run(()=>{const f=new Function('x','return '+text.replace(/sqrt/g,'Math.sqrt').replace(/sin/g,'Math.sin').replace(/cos/g,'Math.cos').replace(/tan/g,'Math.tan').replace(/pow/g,'Math.pow'));return String(f(0))})}>Calculate</button></>;
else if(path.includes('percentage-calculator')) body=<><div className="form-grid"><Input label="Value" value={a} setValue={setA} type="number"/><Input label="Percentage" value={b} setValue={setB} type="number"/></div><button onClick={()=>setResult(String(n(a)*n(b)/100))}>Calculate</button></>;
else if(path.includes('gst-calculator')) body=<><div className="form-grid"><Input label="Amount" value={a} setValue={setA} type="number"/><Input label="GST %" value={b} setValue={setB} type="number"/></div><button onClick={()=>setResult(`GST: ${(n(a)*n(b)/100).toFixed(2)}\nInclusive total: ${(n(a)*(1+n(b)/100)).toFixed(2)}`)}>Calculate</button></>;
else if(path.includes('emi-calculator')) body=<><div className="form-grid"><Input label="Loan amount" value={a} setValue={setA} type="number"/><Input label="Annual interest %" value={b} setValue={setB} type="number"/><Input label="Tenure years" value={c} setValue={setC} type="number"/></div><button onClick={()=>run(()=>{const P=n(a),r=n(b)/1200,N=n(c)*12;if(!P||!N)return 'Enter loan and tenure';const m=r?P*r*Math.pow(1+r,N)/(Math.pow(1+r,N)-1):P/N;return `Monthly EMI: ${m.toFixed(2)}\nTotal payment: ${(m*N).toFixed(2)}\nTotal interest: ${(m*N-P).toFixed(2)}`})}>Calculate EMI</button></>;
else if(path.includes('simple-interest')) body=<><div className="form-grid"><Input label="Principal" value={a} setValue={setA} type="number"/><Input label="Rate % per year" value={b} setValue={setB} type="number"/><Input label="Time in years" value={c} setValue={setC} type="number"/></div><button onClick={()=>setResult(`Interest: ${(n(a)*n(b)*n(c)/100).toFixed(2)}\nAmount: ${(n(a)*(1+n(b)*n(c)/100)).toFixed(2)}`)}>Calculate</button></>;
else if(path.includes('compound-interest')) body=<><div className="form-grid"><Input label="Principal" value={a} setValue={setA} type="number"/><Input label="Rate %" value={b} setValue={setB} type="number"/><Input label="Years" value={c} setValue={setC} type="number"/><Input label="Compounds/year" value={d} setValue={setD} type="number"/></div><button onClick={()=>setResult(()=>{const A=n(a)*Math.pow(1+n(b)/100/n(d),n(d)*n(c));return `Amount: ${A.toFixed(2)}\nInterest: ${(A-n(a)).toFixed(2)}`})}>Calculate</button></>;
else if(path.includes('discount-calculator')) body=<><div className="form-grid"><Input label="Original price" value={a} setValue={setA} type="number"/><Input label="Discount %" value={b} setValue={setB} type="number"/></div><button onClick={()=>setResult(`Savings: ${(n(a)*n(b)/100).toFixed(2)}\nFinal price: ${(n(a)*(1-n(b)/100)).toFixed(2)}`)}>Calculate</button></>;
else if(path.includes('profit-loss')) body=<><div className="form-grid"><Input label="Cost price" value={a} setValue={setA} type="number"/><Input label="Selling price" value={b} setValue={setB} type="number"/></div><button onClick={()=>setResult(()=>{const diff=n(b)-n(a);return diff>=0?`Profit: ${diff.toFixed(2)}\nProfit %: ${(diff/n(a)*100).toFixed(2)}%`:`Loss: ${(-diff).toFixed(2)}\nLoss %: ${(-diff/n(a)*100).toFixed(2)}%`})}>Calculate</button></>;
else if(path.includes('average-calculator')) body=<><label className="field">Numbers (comma separated)<textarea value={text} onChange={e=>setText(e.target.value)}/></label><button onClick={()=>run(()=>{const x=text.split(',').map(Number).filter(v=>!isNaN(v));if(!x.length)throw 0;return `Average: ${(x.reduce((p,v)=>p+v,0)/x.length).toFixed(4)}\nMin: ${Math.min(...x)}\nMax: ${Math.max(...x)}\nSum: ${x.reduce((p,v)=>p+v,0)}`})}>Calculate</button></>;
else if(path.includes('bmi-calculator')) body=<><div className="form-grid"><Input label="Weight (kg)" value={a} setValue={setA} type="number"/><Input label="Height (cm)" value={b} setValue={setB} type="number"/></div><button onClick={()=>{const bmi=n(a)/Math.pow(n(b)/100,2);setResult(`BMI: ${bmi.toFixed(1)}\n${bmi<18.5?'Underweight':bmi<25?'Normal range':bmi<30?'Overweight':'Obesity range'}`)}}>Calculate BMI</button></>;
else if(path.includes('bmr-calculator')) body=<><div className="form-grid"><Input label="Weight kg" value={a} setValue={setA} type="number"/><Input label="Height cm" value={b} setValue={setB} type="number"/><Input label="Age years" value={c} setValue={setC} type="number"/></div><label className="field">Sex<select value={d} onChange={e=>setD(e.target.value)}><option value="m">Male</option><option value="f">Female</option></select></label><button onClick={()=>setResult(`Estimated BMR: ${(10*n(a)+6.25*n(b)-5*n(c)+(d==='f'?-161:5)).toFixed(0)} kcal/day`)}>Calculate BMR</button></>;
else if(path.includes('sip-calculator')) body=<><div className="form-grid"><Input label="Monthly investment" value={a} setValue={setA} type="number"/><Input label="Annual return %" value={b} setValue={setB} type="number"/><Input label="Years" value={c} setValue={setC} type="number"/></div><button onClick={()=>setResult(()=>{const m=n(b)/1200,N=n(c)*12,P=n(a);const fv=P*((Math.pow(1+m,N)-1)/m)*(1+m);return `Estimated value: ${fv.toFixed(2)}\nInvested: ${(P*N).toFixed(2)}\nEstimated gain: ${(fv-P*N).toFixed(2)}`})}>Calculate SIP</button></>;
else if(path.includes('fd-calculator')) body=<><div className="form-grid"><Input label="Principal" value={a} setValue={setA} type="number"/><Input label="Annual rate %" value={b} setValue={setB} type="number"/><Input label="Years" value={c} setValue={setC} type="number"/></div><button onClick={()=>setResult(`Maturity: ${(n(a)*Math.pow(1+n(b)/100,n(c))).toFixed(2)}`)}>Calculate</button></>;
else if(path.includes('cagr-calculator')) body=<><div className="form-grid"><Input label="Starting value" value={a} setValue={setA} type="number"/><Input label="Ending value" value={b} setValue={setB} type="number"/><Input label="Years" value={c} setValue={setC} type="number"/></div><button onClick={()=>setResult(`CAGR: ${((Math.pow(n(b)/n(a),1/n(c))-1)*100).toFixed(2)}%`)}>Calculate</button></>;
else if(path.includes('age-calculator')) body=<><Input label="Date of birth" value={text} setValue={setText} type="date"/><button onClick={()=>run(()=>{const d=new Date(text);const now=new Date();let y=now.getFullYear()-d.getFullYear(),m=now.getMonth()-d.getMonth(),day=now.getDate()-d.getDate();if(day<0){m--;day+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}return `${y} years, ${m} months, ${day} days`})}>Calculate Age</button></>;
else if(path.includes('date-difference')) body=<><div className="form-grid"><Input label="Start date" value={a} setValue={setA} type="date"/><Input label="End date" value={b} setValue={setB} type="date"/></div><button onClick={()=>setResult(`${Math.abs((new Date(b).getTime()-new Date(a).getTime())/86400000)} days`)}>Calculate</button></>;
else if(path.includes('time-duration')) body=<><div className="form-grid"><Input label="Start" value={a} setValue={setA} type="time"/><Input label="End" value={b} setValue={setB} type="time"/></div><button onClick={()=>{let x=new Date('2000-01-01T'+a),y=new Date('2000-01-01T'+b);if(y<x)y.setDate(y.getDate()+1);const m=(y.getTime()-x.getTime())/60000;setResult(`${Math.floor(m/60)} hours ${m%60} minutes`)}}>Calculate</button></>;
else if(path.includes('gcd-lcm')) body=<><div className="form-grid"><Input label="A" value={a} setValue={setA} type="number"/><Input label="B" value={b} setValue={setB} type="number"/></div><button onClick={()=>{let x=Math.abs(n(a)),y=Math.abs(n(b));const g=(u:number,v:number)=>v?g(v,u%v):u;const z=g(x,y);setResult(`GCD: ${z}\nLCM: ${z?Math.abs(x*y)/z:0}`)}}>Calculate</button></>;
else if(path.includes('square-root')) body=<><Input label="Number" value={a} setValue={setA} type="number"/><button onClick={()=>setResult(String(Math.sqrt(n(a))))}>Calculate</button></>;
else if(path.includes('fraction-calculator')) body=<><div className="form-grid"><Input label="Fraction A (e.g. 1/2)" value={a} setValue={setA}/><Input label="Fraction B (e.g. 3/4)" value={b} setValue={setB}/></div><button onClick={()=>run(()=>{const f=(s:string)=>{const[z,q]=s.split('/').map(Number);return[z,q]};const[x,y]=f(a),[u,v]=f(b);return `A+B = ${(x*v+u*y)+'/'+(y*v)}\nA-B = ${(x*v-u*y)+'/'+(y*v)}\nA×B = ${(x*u)+'/'+(y*v)}\nA÷B = ${(x*v)+'/'+(y*u)}`})}>Calculate</button></>;
else if(path.includes('converter')) body=<Converter path={path} a={a} setA={setA} b={b} setB={setB} result={result} setResult={setResult}/>;
else if(path.includes('number-to-words')) body=<><Input label="Number" value={a} setValue={setA} type="number"/><button onClick={()=>setResult(toWords(Math.floor(n(a))))}>Convert</button></>;
else if(path.includes('roman-numeral')) body=<><Input label="Number or Roman numeral" value={text} setValue={setText}/><button onClick={()=>setResult(/^\d+$/.test(text)?toRoman(n(text)):String(roman(text))) }>Convert</button></>;
else if(path.includes('json-formatter')) body=<TextTransform text={text} setText={setText} result={result} setResult={setResult} action="format"/>;
else if(path.includes('json-minifier')) body=<TextTransform text={text} setText={setText} result={result} setResult={setResult} action="minify"/>;
else if(path.includes('base64-encoder')) body=<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Text..."/><button onClick={()=>setResult(btoa(unescape(encodeURIComponent(text))))}>Encode</button></>;
else if(path.includes('base64-decoder')) body=<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Base64..."/><button onClick={()=>run(()=>decodeURIComponent(escape(atob(text))))}>Decode</button></>;
else if(path.includes('url-encoder')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(encodeURIComponent(text))}>Encode URL</button></>;
else if(path.includes('url-decoder')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>run(()=>decodeURIComponent(text))}>Decode URL</button></>;
else if(path.includes('uuid-generator')) body=<><button onClick={()=>setResult(crypto.randomUUID())}>Generate UUID</button></>;
else if(path.includes('password-generator')) body=<PasswordGen/>;
else if(path.includes('random-number')) body=<><div className="form-grid"><Input label="Minimum" value={a} setValue={setA} type="number"/><Input label="Maximum" value={b} setValue={setB} type="number"/></div><button onClick={()=>setResult(String(Math.floor(Math.random()*(n(b)-n(a)+1))+n(a)))}>Generate</button></>;
else if(path.includes('random-string')) body=<><Input label="Length" value={a} setValue={setA} type="number"/><button onClick={()=>setResult(Array.from(crypto.getRandomValues(new Uint32Array(n(a)||16)),x=>'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'[x%62]).join(''))}>Generate</button></>;
else if(path.includes('word-counter')) body=<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Type or paste text..."/><div className="stats"><b>{text.trim()?text.trim().split(/\s+/).length:0}</b> words <b>{text.length}</b> characters <b>{text.split(/[.!?]+/).filter(Boolean).length}</b> sentences</div></>;
else if(path.includes('case-converter')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><div className="button-row"><button onClick={()=>setText(text.toUpperCase())}>UPPERCASE</button><button onClick={()=>setText(text.toLowerCase())}>lowercase</button><button onClick={()=>setText(text.replace(/\b\w/g,x=>x.toUpperCase()))}>Title Case</button></div></>;
else if(path.includes('text-cleaner')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setText(text.replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim())}>Clean Text</button></>;
else if(path.includes('duplicate-lines')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setText([...new Set(text.split('\n'))].join('\n'))}>Remove Duplicates</button></>;
else if(path.includes('text-sorter')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setText(text.split('\n').sort((x,y)=>x.localeCompare(y)).join('\n'))}>Sort Lines</button></>;
else if(path.includes('reverse-text')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setText([...text].reverse().join(''))}>Reverse</button></>;
else if(path.includes('reading-time')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(`Approx. ${Math.max(1,Math.ceil((text.trim()?text.trim().split(/\s+/).length:0)/200))} minute(s)`)}>Calculate</button></>;
else if(path.includes('sentence-counter')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(`${text.split(/[.!?]+/).filter(x=>x.trim()).length} sentences\n${text.split(/\n\s*\n/).filter(x=>x.trim()).length} paragraphs`)}>Count</button></>;
else if(path.includes('lorem-ipsum')) body=<><Input label="Paragraphs" value={a} setValue={setA} type="number"/><button onClick={()=>setResult(Array.from({length:Math.min(20,Math.max(1,n(a)||3))},()=>`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere, neque at facilisis pretium, lorem ipsum luctus sem.`).join('\n\n'))}>Generate</button></>;
else if(path.includes('sha256')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={async()=>setResult(await hash(text))}>SHA-256</button></>;
else if(path.includes('regex-tester')) body=<><Input label="Regex (without / /)" value={a} setValue={setA}/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Test text"/><button onClick={()=>run(()=>{const r=new RegExp(a,'g');return JSON.stringify(text.match(r)||[],null,2)})}>Test</button></>;
else if(path.includes('color-converter')) body=<><Input label="HEX color" value={text} setValue={setText}/><button onClick={()=>run(()=>{const x=text.replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(x))throw 0;return `RGB: ${parseInt(x.slice(0,2),16)}, ${parseInt(x.slice(2,4),16)}, ${parseInt(x.slice(4,6),16)}`})}>Convert</button></>;
else if(path.includes('timestamp-converter')) body=<><Input label="Unix timestamp (seconds), or leave blank for now" value={text} setValue={setText} type="number"/><button onClick={()=>setResult(new Date(text?Number(text)*1000:Date.now()).toISOString())}>Convert</button></>;
else if(path.includes('html-entity')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'))}>Encode</button></>;
else if(path.includes('html-formatter')||path.includes('css-formatter')||path.includes('javascript-formatter')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(text.replace(/></g,'>\n<').replace(/[{};]/g,m=>m+'\n'))}>Format</button></>;
else if(path.includes('csv-to-json')) body=<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="name,age\nJohn,25"/><button onClick={()=>run(()=>{const rows=text.trim().split('\n').map(r=>r.split(','));const h=rows.shift()||[];return JSON.stringify(rows.map(r=>Object.fromEntries(h.map((k,i)=>[k.trim(),(r[i]||'').trim()]))),null,2)})}>Convert</button></>;
else if(path.includes('json-to-csv')) body=<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder='[{"name":"John","age":25}]'/><button onClick={()=>run(()=>{const arr=JSON.parse(text);const h=Object.keys(arr[0]);return [h.join(','),...arr.map((r:any)=>h.map(k=>String(r[k]??'').replace(/,/g,'"').replace(/"/g,'""')).join(','))].join('\n')})}>Convert</button></>;
else if(path.includes('markdown-to-html')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(text.split('\n').map(x=>x.replace(/^### (.*)$/,'<h3>$1</h3>').replace(/^## (.*)$/,'<h2>$1</h2>').replace(/^# (.*)$/,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')).join('\n'))}>Convert</button></>;
else if(path.includes('text-file-creator')) body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><DownloadText text={text}/></>;
else if(path.includes('qr-code')) body=<><Input label="Text or URL" value={text} setValue={setText}/><button onClick={()=>setResult(`https://quickchart.io/qr?text=${encodeURIComponent(text)}&size=300`)}>Create QR</button><p className="muted">The QR image URL can be opened or downloaded.</p></>;
else if(path.includes('image-')) body=<ImageTool type={path}/>;
else if(path.includes('grammar')||path.includes('spell')||path.includes('sentence-correction')) body=<GrammarTool text={text} setText={setText} setResult={setResult} kind={path}/>;
else body=<><textarea value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setResult(text)}>Process</button></>;
return <main className="tool-page"><section className="page-hero"><div className="container"><Link className="back" to={'/'+slug(tool.category)}>← {tool.category}</Link><p className="kicker">{tool.category.toUpperCase()}</p><h1>{tool.name}</h1><p>{tool.description}</p></div></section><section className="section container"><div className="tool-workspace"><div className="tool-box">{body}{error&&<p className="error">{error}</p>}{result&&<div className="result">{result}</div>}{result&&result.startsWith('http')&&<img className="qr" src={result} alt="Generated QR code"/>}{result&&<DownloadText text={result}/>}</div></div><div className="tool-info"><h2>How to use {tool.name}</h2><p>Enter your values, text or file above and run the tool. Basic processing is designed to happen in your browser whenever practical.</p><h3>Related tools</h3><div className="related">{catalog.filter(t=>t.category===tool.category&&t.path!==tool.path).slice(0,4).map(t=><Card t={t} key={t.path}/>)}</div></div></section></main>}
function TextTransform({text,setText,result,setResult,action}:{text:string;setText:(x:string)=>void;result:string;setResult:(x:string)=>void;action:'format'|'minify'}){return <><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste JSON..."/><button onClick={()=>{try{setResult(action==='format'?JSON.stringify(JSON.parse(text),null,2):JSON.stringify(JSON.parse(text)))}catch{setResult('Invalid JSON')}}}>{action==='format'?'Format JSON':'Minify JSON'}</button></>}
function Converter({path,a,setA,b,setB,result,setResult}:{path:string;a:string;setA:(x:string)=>void;b:string;setB:(x:string)=>void;result:string;setResult:(x:string)=>void}){const units=path.split('/').pop();const maps:any={
'length-converter':{m:1,units:{Meter:1,Kilometer:.001,Centimeter:100,Millimeter:1000,Foot:3.28084,Inch:39.3701,Mile:.000621371}},'weight-converter':{m:1,units:{Kilogram:1,Gram:1000,Pound:2.20462,Ounce:35.274}},'temperature-converter':{special:true,units:{Celsius:0,Fahrenheit:1,Kelvin:2}},'area-converter':{m:1,units:{'Square meter':1,'Square kilometer':1e-6,'Square foot':10.7639,Acre:.000247105}},'volume-converter':{m:1,units:{Liter:1,Milliliter:1000,Gallon:.264172,'Cubic meter':.001}},'speed-converter':{m:1,units:{'km/h':1,mph:.621371,'m/s':.277778,Knot:.539957}},'time-converter':{m:1,units:{Second:1,Minute:1/60,Hour:1/3600,Day:1/86400}},'data-converter':{m:1,units:{Byte:1,KB:1/1024,MB:1/1048576,GB:1/1073741824,TB:1/1099511627776}}};const cfg=maps[units]||maps['length-converter'];const keys=Object.keys(cfg.units);const[from,setFrom]=useState(keys[0]);const[to,setTo]=useState(keys[1]||keys[0]);return <><div className="form-grid"><Input label="Value" value={a} setValue={setA} type="number"/><label className="field">From<select value={from} onChange={e=>setFrom(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label><label className="field">To<select value={to} onChange={e=>setTo(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label></div><button onClick={()=>{let v=n(a);if(cfg.special){const C=from==='Celsius'?v:from==='Fahrenheit'?(v-32)*5/9:v-273.15;v=to==='Celsius'?C:to==='Fahrenheit'?C*9/5+32:C+273.15}else v=v/(cfg.units[from])/1*cfg.units[to];setResult(`${v}`)}}>Convert</button></>}
function PasswordGen(){const[len,setLen]=useState('16');const[out,setOut]=useState('');return <><Input label="Length" value={len} setValue={setLen} type="number"/><button onClick={()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';setOut(Array.from(crypto.getRandomValues(new Uint32Array(Math.min(128,Math.max(4,n(len)||16)))),x=>chars[x%chars.length]).join(''))}}>Generate Password</button>{out&&<div className="result">{out}</div>}</>}
function GrammarTool({text,setText,setResult,kind}:{text:string;setText:(x:string)=>void;setResult:(x:string)=>void;kind:string}){return <><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste English text..."/><button onClick={()=>{let out=text;const fixes:[RegExp,string][]=[[/\bteh\b/gi,'the'],[/\brecieve\b/gi,'receive'],[/\bseperate\b/gi,'separate'],[/\bdefinately\b/gi,'definitely'],[/\bi am\b/gi,'I am'],[/\s+([,.!?])/g,'$1']];fixes.forEach(([r,v])=>{out=out.replace(r,v)});setText(out);setResult(kind.includes('spell')?'Common spelling fixes applied.':'Basic grammar/spelling corrections applied.') }}>Check & Correct</button></>}
function ImageTool({type}:{type:string}){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState('');const[w,setW]=useState('');const[h,setH]=useState('');const[quality,setQuality]=useState('0.8');const process=()=>{if(!file)return;const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');const rw=n(w)||img.width,rh=n(h)||Math.round(img.height*(rw/img.width));canvas.width=rw;canvas.height=rh;const ctx=canvas.getContext('2d')!;ctx.drawImage(img,0,0,rw,rh);const mime=type.includes('jpg-to-png')?'image/png':type.includes('png-to-jpg')?'image/jpeg':type.includes('webp')?'image/webp':file.type;setPreview(canvas.toDataURL(mime,Number(quality)||.8))};img.src=URL.createObjectURL(file)};return <><label className="upload"><Upload/><span>{file?file.name:'Choose an image'}</span><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="form-grid"><Input label="Width px (optional)" value={w} setValue={setW} type="number"/><Input label="Height px (optional)" value={h} setValue={setH} type="number"/><Input label="Quality 0–1" value={quality} setValue={setQuality} type="number"/></div><button onClick={process}>Process Image</button>{preview&&<><img className="preview" src={preview} alt="Processed"/><a className="download" href={preview} download="toolbox-image"><Download size={16}/> Download image</a></>}</>}
async function hash(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const ones=['','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];const tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];function toWords(x:number):string{if(x===0)return'zero';if(x<0)return'minus '+toWords(-x);if(x<20)return ones[x];if(x<100)return tens[Math.floor(x/10)]+(x%10?' '+ones[x%10]:'');if(x<1000)return ones[Math.floor(x/100)]+' hundred'+(x%100?' '+toWords(x%100):'');if(x<1e6)return toWords(Math.floor(x/1000))+' thousand'+(x%1000?' '+toWords(x%1000):'');if(x<1e9)return toWords(Math.floor(x/1e6))+' million'+(x%1e6?' '+toWords(x%1e6):'');return toWords(Math.floor(x/1e9))+' billion'+(x%1e9?' '+toWords(x%1e9):'')}
function toRoman(num:number){const vals:[[number,string]]|any=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let s='';for(const[v,r]of vals)while(num>=v){s+=r;num-=v}return s||'0'}function roman(s:string){const m:any={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};let z=0,prev=0;for(const ch of s.toUpperCase().split('').reverse()){const v=m[ch]||0;z+=v<prev?-v:v;prev=Math.max(prev,v)}return z}
function App(){const loc=useLocation();const[dark,setDark]=useState(()=>localStorage.getItem('dark')==='1');const cat=CATS.find(c=>loc.pathname==='/'+slug(c));const tool=catalog.find(t=>t.path===loc.pathname);const all=loc.pathname==='/tools';return <div className={'app '+(dark?'dark':'')}><Header dark={dark} setDark={v=>{setDark(v);localStorage.setItem('dark',v?'1':'0')}}/>{cat?<Category category={cat}/>:tool?<ToolPage tool={tool}/>:all?<main><section className="page-hero"><div className="container"><p className="kicker">COMPLETE DIRECTORY</p><h1>All Tools</h1><p>Browse every utility by category.</p></div></section><section className="section container">{CATS.map(c=><div key={c} style={{marginBottom:45}}><div className="section-head"><h2>{c}</h2><Link className="view-all" to={'/'+slug(c)}>View category <ArrowRight size={15}/></Link></div><div className="tool-grid">{catalog.filter(t=>t.category===c).map(t=><Card t={t} key={t.path}/>)}</div></div>)}</section></main>:<Home/>}<Footer/></div>}
export default App
